# Generated by Django 6.1 on 2026-08-08 16:57

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lsaprofile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['skills'], name='bookings_ls_skills_9866f0_gin'),
        ),
    ]
